PROG = project04 
OBJS = base.o scan.o parse.o project04.o eval.o

CFLAGS = -g

# Pattern rules to avoid explicit rules
%.o : %.c project04.h
	gcc $(CFLAGS) -c -o $@ $<

all : $(PROG)

$(PROG) : $(OBJS)
	gcc $(CFLAGS) -o $@ $(OBJS) -lm

clean :
	rm -rf $(PROG) $(OBJS)
